### ISSUE TITLE
Time Series Executable

### ISSUE THREAD

**Issue by benitoThree** [ThirdAILabs/Universe#237]
Parent issue: #225 
Build a time series executable for Commerce IQ

Our priority is to have a working product by the time they give us the dataset. We will start by wrapping our pandas -> TensorTlow pipeline in an executable that takes in a .toml config file to featurize the input data accordingly.

The next priority is to integrate bolt into this pipeline. To do so, we need to fix BOLT regression and add the capability to output the predictions.

From there, we will add more features such as support for incremental updates using count min sketch, or develop more flexible configurations (this will develop more as we see their data)

### TODO
- [x] Wrap python pipeline in executable that takes in a configuration file. The config file takes in:
    * Column names for target, timestamp, ids.
    * Paths to train / predict files
    * Weeks to predict ahead
    * Path to save prediction
- [x] Add support for static features
- [ ] Implement predict method
- [x] Replace TensorFlow with BOLT
- [ ] Replace Pandas with count-min sketch based time series featurizer
