### ISSUE TITLE
[EPIC] Set up Bolt benchmarks

### ISSUE THREAD

**Issue by JoshEngels** [ThirdAILabs/Universe#297]
# Description
We need a reliable and automated benchmarking process to regularly provide us with data on the quality and speed of our models over time as well as to track the progress of experiments. 

# Sub Issues

- [x] https://github.com/ThirdAILabs/Universe/issues/295

- [ ] https://github.com/ThirdAILabs/Universe/issues/321

- [ ] https://github.com/ThirdAILabs/Universe/issues/322  

- [ ] https://github.com/ThirdAILabs/Universe/issues/373
