### ISSUE TITLE
[Dataset Pipeline] Port time series featurizer block to Python interface

### ISSUE THREAD

**Issue by benitoThree** [ThirdAILabs/Universe#309]
# Problem
The current implementation of the time series featurizer is incompatible with the new dataset interface since it was designed around a completely different interface. It is also quite slow.

# Subtasks
Time estimate: 4 days
- [ ] Design python binding; how does the user use it? 
- [ ] Make sketches contiguous in memory
- [ ] Adapt windowed count and date featurizers to new dataset api
